# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RCF Dev Docs
email: info@cfregisters.org
description: > # this means to ignore newlines until "baseurl:"
  Documentation of the database structure
  and data API for the Comédie Française Registers Project
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hack.cfregisters.org/" # the base hostname & protocol for your site
# twitter_username: jamiefolsom
github_username:

# Build settings
markdown: kramdown

theme: just-the-docs
search_enabled: true
exclude: ["assets/js/"]

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
